global:
  scrape_interval: 1m # Change scrape interval to every 1 minute.
  evaluation_interval: 1m # Change evaluation interval to every 1 minute.

scrape_configs:
  - job_name: "prometheus"
    # metrics_path defaults to '/metrics'
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["localhost:8080"]

  - job_name: 'node'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9100']
